"""empty message

Revision ID: 4b0182c2e842
Revises: 0daa86781737
Create Date: 2020-05-25 00:29:05.643886+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b0182c2e842'
down_revision = '0daa86781737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('router_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owned_by', sa.VARCHAR(length=80), nullable=True),
    sa.Column('destination_pc_id', sa.VARCHAR(length=80), nullable=True),
    sa.Column('hop_cost', sa.Integer(), nullable=True),
    sa.Column('neighbour', sa.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('router_table')
    # ### end Alembic commands ###
