"""empty message

Revision ID: 0daa86781737
Revises: 
Create Date: 2020-05-24 23:06:37.398017+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0daa86781737'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neighbours',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('router_name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('neighbour', sa.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    number = op.create_table('number',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routers',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('router_name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('router_port', sa.Integer(), nullable=True),
    sa.Column('pc_id', sa.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(number,
        [
            {'id': 0, 'count': 0}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routers')
    op.drop_table('number')
    op.drop_table('neighbours')
    # ### end Alembic commands ###
